<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- EN: xUnit v3 test projects are executables. TR: xUnit v3 test projeleri çalıştırılabilir dosyadır. -->
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MyWorkplace.AppHost\MyWorkplace.AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="Aspire.Hosting.Testing" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
